FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
COPY Backend/package.json ./Backend/package.json

RUN npm install

COPY Backend ./Backend

WORKDIR /app/Backend

CMD ["npm", "run", "start:dev"]
