FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
COPY Frontend/package.json ./Frontend/package.json

RUN npm install

COPY Frontend ./Frontend

WORKDIR /app/Frontend

CMD ["npm", "run", "dev"]
