export const INCIDENT_CAUSES = {
  TIMEOUT: 'TIMEOUT',
  CONNECTION_ERROR: 'CONNECTION_ERROR',
  TLS_ERROR: 'TLS_ERROR',
  STATUS_CODE: 'STATUS_CODE',
  ASSERTION_FAILED: 'ASSERTION_FAILED',
  DEGRADED: 'DEGRADED',
} as const;

export type IncidentCause = (typeof INCIDENT_CAUSES)[keyof typeof INCIDENT_CAUSES];
