import { ROLES, type Role } from './roles';
import { PERMISSIONS, type Permission } from './permissions';

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const MEMBER_PERMISSIONS: Permission[] = [
  PERMISSIONS.ORGANIZATION_READ,
  PERMISSIONS.PROJECT_READ,
  PERMISSIONS.PROJECT_CREATE,
  PERMISSIONS.PROJECT_UPDATE,
  PERMISSIONS.MONITOR_CREATE,
  PERMISSIONS.MONITOR_READ,
  PERMISSIONS.MONITOR_UPDATE,
  PERMISSIONS.MONITOR_DELETE,
  PERMISSIONS.INCIDENT_READ,
  PERMISSIONS.INCIDENT_ACKNOWLEDGE,
  PERMISSIONS.INCIDENT_RESOLVE,
  PERMISSIONS.ALERT_RULE_MANAGE,
  PERMISSIONS.NOTIFICATION_CHANNEL_MANAGE,
  PERMISSIONS.STATUS_PAGE_MANAGE,
];

const VIEWER_PERMISSIONS: Permission[] = [
  PERMISSIONS.ORGANIZATION_READ,
  PERMISSIONS.PROJECT_READ,
  PERMISSIONS.MONITOR_READ,
  PERMISSIONS.INCIDENT_READ,
];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.OWNER]: ALL_PERMISSIONS,
  [ROLES.ADMIN]: [
    ...MEMBER_PERMISSIONS,
    PERMISSIONS.MEMBERSHIP_MANAGE,
    PERMISSIONS.PROJECT_DELETE,
    PERMISSIONS.API_KEY_MANAGE,
  ],
  [ROLES.MEMBER]: MEMBER_PERMISSIONS,
  [ROLES.VIEWER]: VIEWER_PERMISSIONS,
};
