export const ALERT_TRIGGERS = {
  INCIDENT_CREATED: 'INCIDENT_CREATED',
  INCIDENT_RESOLVED: 'INCIDENT_RESOLVED',
  INCIDENT_ACKNOWLEDGED: 'INCIDENT_ACKNOWLEDGED',
  MONITOR_DEGRADED: 'MONITOR_DEGRADED',
  MONITOR_FLAPPING: 'MONITOR_FLAPPING',
  CERT_EXPIRING: 'CERT_EXPIRING',
} as const;

export type AlertTrigger = (typeof ALERT_TRIGGERS)[keyof typeof ALERT_TRIGGERS];

export const ALERT_DECISION_REASONS = {
  MATCHED: 'MATCHED',
  DEDUPED: 'DEDUPED',
  THROTTLED: 'THROTTLED',
  SUPPRESSED_ACKNOWLEDGED: 'SUPPRESSED_ACKNOWLEDGED',
  SUPPRESSED_FLAPPING: 'SUPPRESSED_FLAPPING',
  CHANNEL_UNVERIFIED: 'CHANNEL_UNVERIFIED',
} as const;

export type AlertDecisionReason = (typeof ALERT_DECISION_REASONS)[keyof typeof ALERT_DECISION_REASONS];
